# docker-compose.yml
services:
  db:
    container_name: umanni-pg
    image: postgres:17
    environment:
      POSTGRES_USER: umanni
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: umanni_users_production
    volumes:
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    networks:
      - umanni-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umanni -d umanni_users_production"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: umanni-redis
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - umanni-test
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    container_name: umanni-users
    build: .
    ports:
      - "3000:80"
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DB_HOST=umanni-pg
      - POSTGRES_USER=umanni
      - POSTGRES_PASSWORD=secret
      - APP_ORIGIN=http://localhost:3000
      - REDIS_URL=redis://umanni-redis:6379/1
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RAILS_ENV=development
      - RACK_ENV=development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - umanni-test

volumes:
  pg_data:
  redis_data:

networks:
  umanni-test:
    # If you created the network manually earlier (docker network create umanni-test),
    # uncomment the line below and delete 'driver: bridge'
    # external: true 
    driver: bridge